language: node_js
node_js:
- 8
script:
- npm run eslint
- npm run flow
- npm run test
before_deploy: npm run postversion
deploy:
  skip_cleanup: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    tags: true
    repo: intel-hpdd/view-server
