jobs:
  include:
    - stage: test
      name: "copr build test"
      script:
        - export SPEC=iml-view-server.spec
        - docker run -it -e SPEC="$SPEC" -e LOCAL_ONLY="True" -v $(pwd):/build:rw imlteam/copr
        - ((`find _topdir/RPMS -name *.rpm | wc -l` > 0))
    - stage: test
      name: "Lint & Test"
      language: node_js
      node_js: "10"
      cache: npm
      script:
        - npm run eslint
        - npm run flow
        - npm run test
    - stage: deploy-npm
      name: "npm Deploy"
      language: node_js
      node_js: "10"
      before_deploy:
        - npm i --ci
        - npm run postversion
      deploy:
        provider: npm
        skip_cleanup: true
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        on:
          all_branches: true
    - stage: cd
      name: "Continuous Deployment"
      language: generic
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-devel
        - export PACKAGE=iml-view-server
        - export SPEC=iml-view-server.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr
    - stage: deploy-copr-r5.0
      name: "Copr deploy"
      language: generic
      script:
        - export OWNER=managerforlustre
        - export PROJECT=manager-for-lustre-5.1
        - export PACKAGE=iml-view-server
        - export SPEC=iml-view-server.spec
        - docker run -it -e OWNER="$OWNER" -e PROJECT="$PROJECT" -e PACKAGE="$PACKAGE" -e SPEC="$SPEC" -e PROD="true" -e KEY="$encrypted_253525cedcf6_key" -e IV="$encrypted_253525cedcf6_iv" -v $(pwd):/build:rw imlteam/copr

stages:
  - test
  - name: cd
    if: branch = master AND type = push AND fork = false
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+-1.*$
  - name: deploy-copr-r5.0
    if: branch =~ ^v\d+\.\d+\.\d+-.+-r5\.1$
