language: node_js
node_js:
  - 8
jobs:
  include:
    - stage: test
      env: Type='Test Checks'
      script:
        - npm run eslint
        - npm run flow
        - npm run test
    - stage: deploy-npm
      env: Type='NPM Deploy'
      before_deploy: npm postversion
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          all_branches: true
          repo: whamcloud/view-server
stages:
  - test
  - name: deploy-npm
    if: branch =~ ^v\d+\.\d+\.\d+$
